id: 4a5da77a29424179a152c9bc30e408be
initial_creation_type: ocr
source_metadata:
  volumes:
    3d0ff77ec6244d749cb20297c43036e7:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: རང་བཞིན་གྲུབ་པ་མེད་པའི་གཞིའི་མན་ངག།
      total_pages: 1953
      volume_number: 27
