id: DDF0B8BE7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T08:59:07+00:00'
last_modified: '2022-05-26T11:32:53.795018+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4c52:
      image_group_id: I1PD95872
      title: རང་བཞིན་གྲུབ་པ་མེད་པའི་གཞིའི་མན་ངག།
      total_pages: 1953
      order: 27
      base_file: 4c52.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
